### ISSUE TITLE
ReferenceError: failureMessage is not defined

### ISSUE THREAD

**Issue by mirague** [SocketCluster/socketcluster-server#5]
In `strict` mode using `socketcluster-server@4.2.6` we receive the following error when a socket **closes**:

```
/Users/mirague/Projects/pigeon/node_modules/socketcluster-server/scsocket.js:191
        failureMessage = 'Socket connection failed for unknown reasons';
                       ^

ReferenceError: failureMessage is not defined
    at Emitter.SCSocket._onSCClose (/Users/mirague/Projects/pigeon/node_modules/socketcluster-server/scsocket.js:191:24)
    at WebSocket.<anonymous> (/Users/mirague/Projects/pigeon/node_modules/socketcluster-server/scsocket.js:70:10)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at WebSocket.cleanupWebsocketResources (/Users/mirague/Projects/pigeon/node_modules/socketcluster-server/node_modules/ws/lib/WebSocket.js:927:10)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

This is because `failureMessage` is never defined (`var failureMessage;`). Is this intended behaviour? Right now we're forced to run without `use strict` mode, which is unacceptable for production.

**Comment by jondubois** [comment]
@mirague Thanks for the PR, I merged this and published the updated socketcluster-server to npm https://www.npmjs.com/package/socketcluster-server v4.2.7

**Comment by mirague** [comment]
Thanks @jondubois !
